### ISSUE TITLE
Animation doesn't seem to make selections

### ISSUE THREAD

**Issue by DaltonRuer** [wuzhong-zhu/OneDimensionAnimationPane#2]
I press Play. The first dimension value is selected. Screen keeps refreshing and repainting charts but the rest of the values are never selected. Values in charts remain the same as they are for the first selection, but they are repainted.

**Comment by Feras85** [comment]
Same Issue here.

**Comment by wuzhong-zhu** [comment]
May I know which version of sense you are using?

**Comment by Feras85** [comment]
Sure. I tested it on Qlik Sense Desktop 3.1 SR4. I have an enterprise server; however, I didn't try it on it because it has not worked on the desktop.

**Comment by wuzhong-zhu** [comment]
I just tried it on sense with same version, it worked. Could you try it with any of the out of box apps like "helpdesk management" and see if it works? The responding time may be long in big apps and hence the extension does not show properly. In this case you can set a longer time interval so there is more time for calculation.

**Comment by Feras85** [comment]
I just did on Sales Discovery App. I see that the index is changing; however, I see the selection is stuck at first selection. (Same Issue)

**Comment by wuzhong-zhu** [comment]
Whats the dimension you used in sales discovery app? Trying to replicate the problem.

**Comment by Feras85** [comment]
=[State-USStates.Name]

**Comment by wuzhong-zhu** [comment]
Hey guys could you download the newest update to try again? I dont know what I have done but it seems to work now.
Give me an update on the result.
Thanks

**Comment by Feras85** [comment]
Same Issue bro.

**Comment by sokeefe14** [comment]
Same issue here. Any updates? I'm on version 3.2.

**Comment by rognerud** [comment]
If you change 
			if(data[0][0].qState=="S" && maxCnt>1){
to 
			if(data[0][0].qState=="A" && maxCnt>1){
it works.

**Comment by wuzhong-zhu** [comment]
Hi Rognerud, I have checked your fork and really impressed by your modification. and progress bar is great too. Would you do a merge? However I will have to change the logic of selection after merge

To all, hey I finally replicate the problem, like FINALLY. Will change the logic as soon as I can.
The problem is with the data eingine. The return data page structure is modified hence it freezes at the second element.

**Comment by rognerud** [comment]
Thanks! 

I did not understand the sorting mechanism, but I think I`ve fixed it now.
